-- Generated by nwg-displays on 2026-06-14 at 18:17:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x1080",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "1920x1080",
    scale = 1.0
})
