-- Generated by nwg-displays on 2026-09-11 at 12:33:50. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0,
    mirror = "DP-5",
    vrr = 0
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    mirror = "eDP-1",
    vrr = 0
})
